#!/bin/bash

script=$(cat ~/challenges/playroom/script.py)
script_with_values=$(echo "$script" | sed -e "s/remote()/remote(\"$1\", $2)/g" | sed -e "s/process()/process(\"\.\/$3\")/g")
echo "$script_with_values" > script.py
