#!/bin/sh

cat > ./script.py << EOM
from pwn import *
import time
import subprocess
from functools import reduce

def print_red(str):
	print("\033[91m" + str + "\033[0m")

def genbin(binary_name):
	command = f"genbin ~/challenges/playroom/shellcodes/{binary_name}"
	try:
		return bytes.fromhex(subprocess.check_output(command, shell=True, universal_newlines=True))
	except (subprocess.CalledProcessError, ValueError) as e:
		print(f"An exception occurred: {e}")
		exit(-1)

def rop_chain(chain):     
    for i in range(len(chain)):
        chain[i] = p64(chain[i])
    return reduce(lambda x, y: x + y, chain)


context.terminal = ['tmux', 'splitw', '-h']
#context.log_level = "error"

# breakpoints
b_main = 0xffff


if args["REMOTE"]:
	r = remote("$1", $2)
else:
	r = process("./$3")
	gdb.attach(r, f"""
	# b *{b_main}
	unset env
	set disable-randomization off
	c
	""")

input("wait")
time.sleep(0.5)
r.interactive()
EOM
